name: Build and Deploy Executables

on:
  push:
    tags:
      - 'v*' # 'v'로 시작하는 태그가 푸시될 때 실행

jobs:
  build-and-deploy:
    # Matrix 전략을 사용해 여러 OS에서 동시에 빌드
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }} # Matrix에 지정된 OS에서 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set executable name by OS
        id: set_name
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            echo "EXE_NAME=health_checker" >> $GITHUB_ENV
            echo "DEST_DIR=resources/mac" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" == "Windows" ]; then
            echo "EXE_NAME=health_checker.exe" >> $GITHUB_ENV
            echo "DEST_DIR=resources/win" >> $GITHUB_ENV
          fi

      - name: Build executable with PyInstaller
        run: pyinstaller src/main.py --name ${{ env.EXE_NAME }} --onefile --noconsole

      - name: Push to Front Repository
        uses: cpina/github-action-push-to-another-repo@v1.6.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_FOR_FRONT_REPO }}
        with:
          source-files: 'dist/${{ env.EXE_NAME }}'
          destination-repo: 'AskQL/Front'
          destination-branch: 'master'
          destination-dir: '${{ env.DEST_DIR }}'
          commit-message: 'Deploy AI executable ${{ github.ref_name }} from ${{ runner.os }}'
          user-email: 'actions@github.com'
          user-name: 'github-actions'