name: Build and Deploy Executables

on:
  push:
    tags:
      - 'v*' # 'v'로 시작하는 태그가 푸시될 때 실행

jobs:
  build-and-deploy:
    # Matrix 전략을 사용해 여러 OS에서 동시에 빌드
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }} # Matrix에 지정된 OS에서 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # OS에 따라 실행 파일 이름과 배포 경로를 동적으로 설정
      - name: Set environment variables by OS
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            echo "EXE_NAME=health_checker" >> $GITHUB_ENV
            echo "DEST_DIR=resources/mac" >> $GITHUB_ENV
          elif [ "${{ runner.os }}" == "Windows" ]; then
            echo "EXE_NAME=health_checker.exe" >> $GITHUB_ENV
            echo "DEST_DIR=resources/win" >> $GITHUB_ENV
          fi

      # src/main.py를 빌드하도록 경로 수정
      - name: Build executable with PyInstaller
        run: pyinstaller src/main.py --name ${{ env.EXE_NAME }} --onefile --noconsole

      # 다른 레포지토리로 빌드된 파일 푸시 (안정적인 액션으로 교체)
      - name: Deploy to Front Repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAT_FOR_FRONT_REPO }}
          repository-name: AskQL/Front
          branch: master
          folder: dist # 배포할 파일이 있는 폴더
          target-folder: ${{ env.DEST_DIR }} # Front 레포지토리의 대상 폴더
          clean: false # 대상 폴더를 비우지 않음
          commit-message: 'Deploy AI executable ${{ github.ref_name }} from ${{ runner.os }}'
